apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-content-pv
spec:
  storageClassName: volumen
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/web

