apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-content-pvc
spec:
  storageClassName: volumen
  volumeName: web-content-pv
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
